GET http://localhost:8080 HTTP/1.0
?? status == 404 

GET http://localhost:8080/echo HTTP/1.0
Content-Type: text/html
Authorization: Bearer token
?? header Content-Type == text/html
?? header Authorization == Bearer
